<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALL MAKES   ACURAALFA ROMEOAMCAUDIBM_58cb69</name>
   <tag></tag>
   <elementGuidId>2fc48608-dc3c-42e3-a1fe-206ec4434eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='makes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>makes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>makes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

    ALL MAKES...
   ACURAALFA ROMEOAMCAUDIBMWBROADWAY TRUCKBUICKCADILLACCHEVROLETCHEVROLET TRUCKS, VANS, SUVSCHRYSLERDAEWOODAIHATSUDE LOREANDIAMOND REODODGEDODGE TRUCKS, VANS, SUVSEAGLEFERRARIFIATFORDFORD TRUCKS, VANS, SUVSFREIGHTLINERGEOGMC TRUCKs, VANS, SUVSHINO TRUCKHONDAHUMMERHYUNDAIINFINITIISUZUIVECO TRUCKJAGUARJEEPKENWORTHKIALAMBORGHINILAND ROVERLEXUSLINCOLNMACK TRUCKMAGIRUS-DEUTZMASERATIMAZDAMAZDA TRUCKS,VANS,SUVSMERCEDES BENZMERCURYMERCURY TRUCKS, VANS, SUVSMERKURMGMINIMITSUBISHINAVISTAR - INTERNATIONAL HARVESTERNISSAN/DATSUNOLDSMOBILEPANOZPETERBILTPEUGEOTPLYMOUTHPONTIACPORSCHERENAULTROLLS ROYCE (BENTLEY)SAABSATURNSCIONSMARTSTERLINGSTERLING TRUCKSUBARUSUZUKITOYOTATOYOTA TRUCKS, VANS, SUVSTRIUMPHVOLKSWAGENVOLVOVPGWHITE-GMC-VOLVOYUGO</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;makes&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='makes']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='makeModelForm']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
