<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALL MODELSAstro VanAvalancheAveo Ave_630eb1</name>
   <tag></tag>
   <elementGuidId>0ea3c617-c62d-4c40-9ada-2073bd8c06ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='models']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>models</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>models</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL MODELS...Astro VanAvalancheAveo, Aveo 5Beretta, Corsica w/o tilt wheelBeretta, Corsica w/tilt wheelBlazerC/K Pick Up, Silverado, TyphoonCamaro Camaro w/ ProxCamaro, Z28Caprice PPV (Police &amp; Detective)Captiva SportCavalierCity ExpressCobalt Colorado - Crew, Extended, Regular  CabsColorado - Crew, Extended, Regular  Cabs (Canada)CorvetteCruzeCruze w/ ProxEpicaEquinoxExpressFSR, FRR, FTR HHRImpala Impala w/ ProxImpala, CapriceLuminaLumina APVMalibuMalibu / Malibu MaxMalibu ClassicMalibu w/ ProxMetroModels and years not referenced elsewhere Monte CarloNova NPR, NRR, W4, W5NQROptraOrlando (Canada)PrizmS-10 Pick UpSilverado - 1500 Crew, Extended Cabs, Silverado Hybrid, SSRSilverado - Classic SSSilverado 1500/HD/SS, 2500/HD/3500SonicSparkSpectrumSprintSuburbanSuburban w/ ProxTahoe Tahoe w/ ProxTahoe, G VANTrackerTrailblazerTraverseTrax (Canada)Uplander Mini VanVenture VanVivantVoltW4 &amp; W5, Kodiak Trucks, C4500-C8500</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;models&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='models']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='makeModelForm']/select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
   </webElementXpaths>
</WebElementEntity>
