CREATE TABLE autos.[YearMakeModel]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Year] INT NOT NULL,
	Make NVARCHAR(500) NOT NULL,
	Model NVARCHAR(500) NOT NULL,
	KeyBlanks NVARCHAR(500) NULL,
	CodeSeries NVARCHAR(500) NULL,
	ProgramWith NVARCHAR(500) NULL,
	Substitute NVARCHAR(500) NULL,
	Notes NVARCHAR(500) NULL,
	KeyBladeType NVARCHAR(100) NOT NULL,
	IsCloner BIT NOT NULL DEFAULT 0,
	IsTransponder BIT NOT NULL DEFAULT 0,
	IsProx BIT NOT NULL DEFAULT 0,	
	IsVATS BIT NOT NULL DEFAULT 0,
	IsReflashRequired BIT NOT NULL DEFAULT 0,
	IsNoFlyList BIT NOT NULL DEFAULT 0,

	IsActive BIT NOT NULL DEFAULT 1,
	DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	DateModified DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

	CONSTRAINT UQ_autos_YearMakeModel_Year_Make_Model_KeyBladeType UNIQUE (Year, Make, Model, KeyBladeType)

)
