CREATE TABLE stage.[IlcoEntryYearMakeModelKeyBlank]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IlcoEntryId INT NOT NULL,
	Year INT NOT NULL,
	Make NVARCHAR(500) NOT NULL,
	Model NVARCHAR(500) NOT NULL,
	EntryTitle NVARCHAR(500) NOT NULL,
	KeyBlankDetails NVARCHAR(500) NOT NULL,
	CodeSeriesText NVARCHAR(500) NULL,
	SubstituteText NVARCHAR(500) NULL,
	ProgramWithText NVARCHAR(500) NULL,
	NotesText NVARCHAR(500) NULL,
	KeyBladeType NVARCHAR(100) NULL,
	IsCloner BIT NOT NULL DEFAULT 0,
	IsTransponder BIT NOT NULL DEFAULT 0,
	IsProx BIT NOT NULL DEFAULT 0,	
	IsVATS BIT NOT NULL DEFAULT 0,
	IsReflashRequired BIT NOT NULL DEFAULT 0,
	IsNoFlyList BIT NOT NULL DEFAULT 0,
	IsActive BIT NOT NULL DEFAULT 1, 

	DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	DateModified DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

	CONSTRAINT FK_stage_YearMakeModel_stage_IlcoEntry_IlcoEntryId FOREIGN KEY (IlcoEntryId) REFERENCES stage.IlcoEntry (Id),

)
