CREATE TABLE stage.[IlcoEntryYearMakeModel]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IlcoEntryId INT NOT NULL,
	Year INT NOT NULL,
	Make NVARCHAR(500) NOT NULL,
	Model NVARCHAR(500) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	DateModified DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

	CONSTRAINT FK_stage_YearMakeModel_stage_IlcoEntry_IlcoEntryId FOREIGN KEY (IlcoEntryId) REFERENCES stage.IlcoEntry (Id),

)
