CREATE TABLE stage.[IlcoEntry]
(
	MakeName NVARCHAR(100) NOT NULL,
	ModelName NVARCHAR(100) NOT NULL,
	EntryTitle NVARCHAR(500) NOT NULL,
	KeyBlankDetails NVARCHAR(500) NOT NULL,
	CodeSeriesText NVARCHAR(500) NULL,
	SubstituteText NVARCHAR(500) NULL,
	ProgramWithText NVARCHAR(500) NULL,
	NotesText NVARCHAR(500) NULL,
	IsCloner BIT NOT NULL DEFAULT 0,
	IsTransponder BIT NOT NULL DEFAULT 0,
	IsProx BIT NOT NULL DEFAULT 0,	
	IsVATS BIT NOT NULL DEFAULT 0,
	IsReflashRequired BIT NOT NULL DEFAULT 0,
	KeyBladeType NVARCHAR(100) NULL,
	IsActive BIT NOT NULL DEFAULT 1, 
	DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	DateModified DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

	CONSTRAINT PK_stage_IlcoEntry PRIMARY KEY CLUSTERED (MakeName, ModelName, EntryTitle, KeyBlankDetails)
)
GO
